### PR TITLE
Changed the interface

### PR DESCRIPTION
**Pull request by tws9797**
Dear @RomchyFCC, I have made changes about the interfaces. Please review the changes. Thank you!

### CODE REVIEW

**Comment by RomchyFCC** [comment]
@tws9797 no need for dear, you and me are in all aspects equal therefor you are my friend and the official greetings are not needed. I absolutely love what you did here, I checked it out on my local server and it looks great. Unfortunately we are on github and github only hosts pages (that you can check out) on the front end so the PHP scripts you wrote can't be used to show our project :(
I like your work and I am almost inclined to copy and paste all the code in to normal html files, but that would take away from your work. Could you please for the projects sake create new html files?

If you are interested in expanding the idea behind this group we can expand to heroku and create a full stack app there? How does that sound, does it go hand in hand with your project at school?

**Comment by RomchyFCC** [comment]
Also, thanks for creating on the same branch, it would have been a lot easier to merge this time! :)

**Comment by tws9797** [comment]
Thanks for the review! I will submit the files again using html files. Can you give me more details about the full stack app ?

**Comment by RomchyFCC** [comment]
As in what a full stack app means or what we can do to create one full stack webpage for free on the internet?

**Pull request closed without merging**
