### PR TITLE
Slider for the golf project

### PR DESCRIPTION
**Pull request by mills3**
An attempt to replicate the victorhills slider

### CODE REVIEW

**Comment by RomchyFCC** [comment]
I absolutely love it, thanks for the contribution mills! :)

**Comment by mills3** [comment]
Thanks, I just noticed i left a commented out iframe. I think authors can edit files online if that would be easier? Or i will make a PR to clean it up!

**Comment by RomchyFCC** [comment]
Nah no need, I wouldn't want to bother you over a comment tag. I already removed it :)

**Comment by RomchyFCC** [comment]
Oh wait, it doesn't look quite right atm, did you want me to remove the whole comment or just comment out the iframe :O?

**Comment by RomchyFCC** [comment]
OK, removed it completely :D

**Comment by mills3** [comment]
Thanks for doing that. Is there a name for this golf club? Roman Hills Golf Club perhaps ; )

**Comment by RomchyFCC** [comment]
Not atm, but you gave me a great idea, we need a new name for our group :) got any ideas :O?

**Pull request merged**
