### PR TITLE
Added my FCC username

### PR DESCRIPTION
**Pull request by mills3**
Hi, this is my first pull request ever, is this still active?

### CODE REVIEW

**Comment by RomchyFCC** [comment]
It sure is, waiting for a hero to take on the issue we have :) will it be you ?

If any changes are made to the repo, you should make a git pull and see the changes locally, then contribute again till this becomes second nature

**Comment by mills3** [comment]
Yeah, i will do this tonight. NOOB QUESTION: do i 'claim' an issue or just make the changes and submit a pull request?

**Comment by DarrenfJ** [comment]
I would say 'claim'it by commenting that you want to take it on..

Thanks for playing along!

😃

**Comment by DarrenfJ** [comment]
@mills3 you can also claim it here:

https://forum.freecodecamp.org/t/git-and-github-practice-for-all-us-noobies/171808/16

**Comment by mills3** [comment]
Ok thanks, i thought there was maybe a button for accepting issues that i couldn't see.

**Pull request merged**
