### PR TITLE
Add John Hanna to contributors

### PR DESCRIPTION
**Pull request by jphanna**
Add John Hanna to contributors.html and contributors.css

### CODE REVIEW

**Comment by RomchyFCC** [comment]
Hey, great stuff! Thanks for the contribution. You are welcome to tackle some of our issues :)

**Comment by jphanna** [comment]
Thanks @RomchyFCC !  I have a question tho. As you probably saw, I had 3 commits, my initial commit, an edit abd this crazy merge branch commit. How could I have handled that better?

**Comment by RomchyFCC** [comment]
Well that's no problem, you could just git add . and git commit in longer increments. Or maybe test your code locally before committing it, so silly trivial mistakes like a semicolon don't get added on a separate commit. Other than that I believe you did a good job and I think you did everything right. Did that answer your question? We can go into specifics of your workflow if you want more feedback :)

**Comment by jphanna** [comment]
Thanks again @RomchyFCC for the advice. I just need to make sure I am not in such a hurry to commit. :)

**Pull request merged**
