### PR TITLE
Addme

### PR DESCRIPTION
**Pull request by dcookwebdev**
Add me!
I'm a noob!

### CODE REVIEW

**Comment by RomchyFCC** [comment]
@dcookwebdev Thank you for contributing! The code looks good and I see you already added yourself to the list which I am also grateful for! You are welcome to stay and help us tackle a few issues that pop up in the near future!

**Comment by dcookwebdev** [comment]
Thank you @RomchyFCC. Once I get back on my computer I will also do my upstream fetch / merge. I am still curious to see what that’s like. 
I really appreciate that I could go through all the steps to make a PR. There’s *a lot* of moving parts and just reading about it doesn’t help to understand. 
So I’m looking forward to more practice. I will come back to this when I get a moment and see if I can contribute/change something else.

**Comment by RomchyFCC** [comment]
Awesome, I love to hear that!

**Comment by dcookwebdev** [comment]
@RomchyFCC in the readme it tells me to delete the branch I made. I did that, but is that necessary? What's the reason to delete a branch? I see it shows up here too that I deleted it which is interesting.

**Comment by dcookwebdev** [comment]
@RomchyFCC don't worry about replying late it's all good. Thanks for the explanation! I guess it all depends as well on what kind of git-flow a team may want to use. Thanks for your help!

**Pull request merged**
