### PR TITLE
added my name

### PR DESCRIPTION
**Pull request by usunil0**

### CODE REVIEW

**Comment by RomchyFCC** [comment]
Hey @usunil0 thanks for contributing, welcome!
I skimmed the code you submitted and noticed that your html element had an ID attribute but you tried to call it by class with the dot in your css. 
ID selectors get called via the `#` selector.
You are welcome to contribute more :)

**Comment by usunil0** [comment]
O_o Oops did tht in a hurry maybe. Thnkx  @RomchyFCC for correcting it. will try  to contribute more :)

**Comment by usunil0** [comment]
should i deleting this branch i made as it is showing that it can be safely deleted?

**Comment by RomchyFCC** [comment]
No worries, that's why we are here :)
You can safely delete the branch!
You can stay up to date with this repository through `git remote add upstream https://github.com/RomchyFCC/GitHub-Practice-For-All.git`.
Details are available [here](https://github.com/RomchyFCC/GitHub-Practice-For-All#how-to-sync-your-local-repo-with-the-original-repo).

**Pull request merged**
